export const FETCH_CATEGORY_BY_PAGE = 'FETCH_CATEGORY_BY_PAGE'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const ADD_AND_UPDATE_CATEGORY = 'ADD_AND_UPDATE_CATEGORY'
export const ADD_AND_UPDATE_CATEGORY_ERROR = 'ADD_AND_UPDATE_CATEGORY_ERROR'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_ERROR= 'DELETE_CATEGORY_ERROR'
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const SET_CATEGORY = "SET_CATEGORY"